### PR TITLE
layout_util: fix passing an rvalue to WEXITSTATUS

### LINKED ISSUE #588: Geeqie fails to build on macOS
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
1.4

Config:
<details>
<pre>
     Config results:
    -=-=-=-=-=-=-=-=-

Package:
  Name:          geeqie
  Version:       1.4

Architecture:
  UNIX:          yes
  Win32:         no (native: no)

Flags:
  Geeqie:        
  DEFS:          -DHAVE_CONFIG_H
  CPPFLAGS:      
  CFLAGS:         -Werror -Wno-error=deprecated-declarations -Wno-error=sign-compare -Wno-error=return-type
  CXXFLAGS:      -g -O2
  Gtk:           -D_REENTRANT -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/glib/2.54.3/include/gio-unix-2.0/ -I/usr/local/Cellar/glib/2.54.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.6/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0_1/include/pixman-1 -I/usr/local/Cellar/cairo/1.14.12/include/cairo -I/usr/local/Cellar/gdk-pixbuf/2.36.11/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/atk/2.26.1/include/atk-1.0 -I/usr/local/Cellar/libepoxy/1.4.3/include -I/usr/local/Cellar/graphite2/1.3.10/include -I/usr/local/Cellar/harfbuzz/1.7.5/include/harfbuzz -I/usr/local/Cellar/pango/1.40.14/include/pango-1.0 -I/usr/local/Cellar/gtk+3/3.22.26/include/gtk-3.0
  Glib:          -D_REENTRANT -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/glib/2.54.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include
  Thread:        -L/usr/local/Cellar/glib/2.54.3/lib -L/usr/local/opt/gettext/lib -lgthread-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation
  Others:	 -ljpeg -ltiff -L/usr/local/Cellar/little-cms2/2.9/lib -llcms2 -L/usr/local/Cellar/exiv2/0.26/lib -lexiv2     

Localization:
  NLS support:   yes
  LINGUAS:        ar be bg ca cs da de el eo es et eu fi fr hu id it ja ko nb nl pl pt_BR ro ru sk sl sr@latin sr sv th tlh tr uk vi zh_CN zh_TW

Settings:
  Developer:     no
  Debug flags:   no
  Debug log:     yes
  Deprecated:    no

Support:
  LCMS:          yes
  Exiv2:	 yes
  Lirc:          no
  Clutter:       no
  Libchamplain:		disabled
  Libchamplain-gtk:	disabled
  Lua:	         no
  FFmpegthumbnailer:	no

Documentation:
  Doxygen:       
  doc-tool:
</pre>
</details>

### OS / DISTRIBUTION
macOS 10.13.3

### SUMMARY
Geeqie 1.4 fails to build on macOS 10.13, using Apple clang 9.0.0 and GCC 7.3.0. Here's the error message when building using clang:

```
layout_util.c:515:16: error: cannot take the address of an rvalue of type 'int'
                run_result = WEXITSTATUS(runcmd(command));
                             ^           ~~~~~~~~~~~~~~~
/usr/include/sys/wait.h:144:26: note: expanded from macro 'WEXITSTATUS'
#define WEXITSTATUS(x)  ((_W_INT(x) >> 8) & 0x000000ff)
                          ^      ~
/usr/include/sys/wait.h:131:28: note: expanded from macro '_W_INT'
#define _W_INT(w)       (*(int *)&(w))  /* convert union wait to int */
                                 ^ ~
1 error generated.
```

Full logs here: https://gist.github.com/mistydemeo/cec398ddb71580bdd595280c7619339b

### STEPS TO REPRODUCE
1. Stage the source code, run `autogen.sh`, and configure with `--enable-gtk3`.
2. Run `make`.

### PR DESCRIPTION
**Pull request by mistydemeo**
Fixes #588.

Looks like that bug can be fixed just by making sure the return value of `runcmd` is assigned to a variable before passing it to `WEXITSTATUS`.

### CODE REVIEW

**Comment by caclark** [comment]
Thanks
Fixed in commit 75c7df8b9 at geeqie.org
