### ISSUE TITLE
fails to compile with lua-5.4

### ISSUE THREAD

**Issue by oneforall2** [BestImageViewer/geeqie#1117]
* Bug Report

### GEEQIE VERSION

``2.1`

```

<!-- What GTK toolkit is used to compile Geeqie? If you compile geeqie
yourself, please paste the config result at the end of configure. -->
```
gtk+-3.0 found: YES 3.24.38 (cached)
```




/usr/bin/ld: lua.cc:(.text+0x26): undefined reference to `luaL_checkudata(lua_State*, int, char const*)'

/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_image_get_path(lua_State*)':
lua.cc:(.text+0x14): undefined reference to `luaL_checktype(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0x26): undefined reference to `luaL_checkudata(lua_State*, int, char const*)'
/usr/bin/ld: lua.cc:(.text+0x3e): undefined reference to `lua_pushstring(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x59): undefined reference to `lua_type(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x63): undefined reference to `lua_typename(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x7a): undefined reference to `lua_pushfstring(lua_State*, char const*, ...)'
/usr/bin/ld: lua.cc:(.text+0x8a): undefined reference to `luaL_argerror(lua_State*, int, char const*)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_image_get_name(lua_State*)':
lua.cc:(.text+0xa4): undefined reference to `luaL_checktype(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0xb6): undefined reference to `luaL_checkudata(lua_State*, int, char const*)'
/usr/bin/ld: lua.cc:(.text+0xce): undefined reference to `lua_pushstring(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0xe9): undefined reference to `lua_type(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0xf3): undefined reference to `lua_typename(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x10a): undefined reference to `lua_pushfstring(lua_State*, char const*, ...)'
/usr/bin/ld: lua.cc:(.text+0x11a): undefined reference to `luaL_argerror(lua_State*, int, char const*)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_image_get_extension(lua_State*)':
lua.cc:(.text+0x134): undefined reference to `luaL_checktype(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0x146): undefined reference to `luaL_checkudata(lua_State*, int, char const*)'
/usr/bin/ld: lua.cc:(.text+0x15e): undefined reference to `lua_pushstring(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x179): undefined reference to `lua_type(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x183): undefined reference to `lua_typename(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x19a): undefined reference to `lua_pushfstring(lua_State*, char const*, ...)'
/usr/bin/ld: lua.cc:(.text+0x1aa): undefined reference to `luaL_argerror(lua_State*, int, char const*)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_image_get_date(lua_State*)':
lua.cc:(.text+0x1c4): undefined reference to `luaL_checktype(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0x1d6): undefined reference to `luaL_checkudata(lua_State*, int, char const*)'
/usr/bin/ld: lua.cc:(.text+0x1f4): undefined reference to `lua_pushnumber(lua_State*, double)'
/usr/bin/ld: lua.cc:(.text+0x211): undefined reference to `lua_type(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x21b): undefined reference to `lua_typename(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x232): undefined reference to `lua_pushfstring(lua_State*, char const*, ...)'
/usr/bin/ld: lua.cc:(.text+0x242): undefined reference to `luaL_argerror(lua_State*, int, char const*)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_image_get_marks(lua_State*)':
lua.cc:(.text+0x264): undefined reference to `luaL_checktype(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0x276): undefined reference to `luaL_checkudata(lua_State*, int, char const*)'
/usr/bin/ld: lua.cc:(.text+0x296): undefined reference to `lua_pushnumber(lua_State*, double)'
/usr/bin/ld: lua.cc:(.text+0x2b9): undefined reference to `lua_type(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x2c3): undefined reference to `lua_typename(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x2da): undefined reference to `lua_pushfstring(lua_State*, char const*, ...)'
/usr/bin/ld: lua.cc:(.text+0x2ea): undefined reference to `luaL_argerror(lua_State*, int, char const*)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_image_get_size(lua_State*)':
lua.cc:(.text+0x304): undefined reference to `luaL_checktype(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0x316): undefined reference to `luaL_checkudata(lua_State*, int, char const*)'
/usr/bin/ld: lua.cc:(.text+0x334): undefined reference to `lua_pushnumber(lua_State*, double)'
/usr/bin/ld: lua.cc:(.text+0x351): undefined reference to `lua_type(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x35b): undefined reference to `lua_typename(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x372): undefined reference to `lua_pushfstring(lua_State*, char const*, ...)'
/usr/bin/ld: lua.cc:(.text+0x382): undefined reference to `luaL_argerror(lua_State*, int, char const*)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_image_get_exif(lua_State*)':
lua.cc:(.text+0x3a2): undefined reference to `luaL_checktype(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0x3b4): undefined reference to `luaL_checkudata(lua_State*, int, char const*)'
/usr/bin/ld: lua.cc:(.text+0x3da): undefined reference to `lua_newuserdatauv(lua_State*, unsigned long, int)'
/usr/bin/ld: lua.cc:(.text+0x3ef): undefined reference to `lua_getfield(lua_State*, int, char const*)'
/usr/bin/ld: lua.cc:(.text+0x3fc): undefined reference to `lua_setmetatable(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x419): undefined reference to `lua_type(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x423): undefined reference to `lua_typename(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x43a): undefined reference to `lua_pushfstring(lua_State*, char const*, ...)'
/usr/bin/ld: lua.cc:(.text+0x44a): undefined reference to `luaL_argerror(lua_State*, int, char const*)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_exif_get_datum(lua_State*)':
lua.cc:(.text+0x476): undefined reference to `luaL_checktype(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0x488): undefined reference to `luaL_checkudata(lua_State*, int, char const*)'
/usr/bin/ld: lua.cc:(.text+0x4a7): undefined reference to `luaL_checklstring(lua_State*, int, unsigned long*)'
/usr/bin/ld: lua.cc:(.text+0x543): undefined reference to `lua_pushnumber(lua_State*, double)'
/usr/bin/ld: lua.cc:(.text+0x55c): undefined reference to `lua_pushnil(lua_State*)'
/usr/bin/ld: lua.cc:(.text+0x577): undefined reference to `lua_pushstring(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x599): undefined reference to `lua_type(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x5a3): undefined reference to `lua_typename(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x5ba): undefined reference to `lua_pushfstring(lua_State*, char const*, ...)'
/usr/bin/ld: lua.cc:(.text+0x5ca): undefined reference to `luaL_argerror(lua_State*, int, char const*)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `luaL_typerror(lua_State*, int, char const*)':
lua.cc:(.text+0x5ed): undefined reference to `lua_type(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x5f7): undefined reference to `lua_typename(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x60c): undefined reference to `lua_pushfstring(lua_State*, char const*, ...)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_init()':
lua.cc:(.text+0x635): undefined reference to `luaL_newstate()'
/usr/bin/ld: lua.cc:(.text+0x644): undefined reference to `luaL_openlibs(lua_State*)'
/usr/bin/ld: lua.cc:(.text+0x654): undefined reference to `lua_createtable(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0x667): undefined reference to `luaL_setfuncs(lua_State*, luaL_Reg const*, int)'
/usr/bin/ld: lua.cc:(.text+0x678): undefined reference to `lua_pushvalue(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x689): undefined reference to `lua_setglobal(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x69a): undefined reference to `luaL_newmetatable(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x6ad): undefined reference to `luaL_setfuncs(lua_State*, luaL_Reg const*, int)'
/usr/bin/ld: lua.cc:(.text+0x6be): undefined reference to `lua_pushstring(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x6cf): undefined reference to `lua_pushvalue(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x6e0): undefined reference to `lua_settable(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x6f1): undefined reference to `lua_pushstring(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x702): undefined reference to `lua_pushvalue(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x713): undefined reference to `lua_settable(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x724): undefined reference to `lua_settop(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x735): undefined reference to `lua_settop(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x745): undefined reference to `lua_createtable(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0x758): undefined reference to `luaL_setfuncs(lua_State*, luaL_Reg const*, int)'
/usr/bin/ld: lua.cc:(.text+0x769): undefined reference to `lua_pushvalue(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x77a): undefined reference to `lua_setglobal(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x78b): undefined reference to `luaL_newmetatable(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x79e): undefined reference to `luaL_setfuncs(lua_State*, luaL_Reg const*, int)'
/usr/bin/ld: lua.cc:(.text+0x7af): undefined reference to `lua_pushstring(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x7c0): undefined reference to `lua_pushvalue(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x7d1): undefined reference to `lua_settable(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x7e2): undefined reference to `lua_pushstring(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x7f3): undefined reference to `lua_pushvalue(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x804): undefined reference to `lua_settable(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x815): undefined reference to `lua_settop(lua_State*, int)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_callvalue(FileData*, char const*, char const*)':
lua.cc:(.text+0x8a4): undefined reference to `lua_createtable(lua_State*, int, int)'
/usr/bin/ld: lua.cc:(.text+0x8b5): undefined reference to `lua_setglobal(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x8cb): undefined reference to `lua_newuserdatauv(lua_State*, unsigned long, int)'
/usr/bin/ld: lua.cc:(.text+0x8e4): undefined reference to `lua_getfield(lua_State*, int, char const*)'
/usr/bin/ld: lua.cc:(.text+0x8f5): undefined reference to `lua_setmetatable(lua_State*, int)'
/usr/bin/ld: lua.cc:(.text+0x906): undefined reference to `lua_setglobal(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x920): undefined reference to `luaL_loadfilex(lua_State*, char const*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x943): undefined reference to `lua_tolstring(lua_State*, int, unsigned long*)'
/usr/bin/ld: lua.cc:(.text+0x97b): undefined reference to `luaL_loadstring(lua_State*, char const*)'
/usr/bin/ld: lua.cc:(.text+0x99a): undefined reference to `lua_pcallk(lua_State*, int, int, int, long, int (*)(lua_State*, int, long))'
/usr/bin/ld: lua.cc:(.text+0x9b1): undefined reference to `lua_tolstring(lua_State*, int, unsigned long*)'
/usr/bin/ld: lua.cc:(.text+0xaa7): undefined reference to `lua_pcallk(lua_State*, int, int, int, long, int (*)(lua_State*, int, long))'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `luaL_typerror(lua_State*, int, char const*)':
lua.cc:(.text+0x61d): undefined reference to `luaL_argerror(lua_State*, int, char const*)'
/usr/bin/ld: src/geeqie.p/lua.cc.o: in function `lua_init()':

**Comment by caclark** [comment]
I am confused how this occurs . Please try:

`rm -r build`
`meson setup build > logfile.txt`
`gzip logfile.txt`


and upload the logfile to here.

**Comment by tomaszg7** [comment]
I noticed it before and tried to debug it but I also was confused :) I didn't find anything wrong.

In my case I had several versions of Lua installed, but meson was finding them correctly and setting linking flags as should be. I was stumped but postponed further investigation for later.

**Comment by oneforall2** [comment]
[meson.build.diff.gz](https://github.com/BestImageViewer/geeqie/files/11805751/meson.build.diff.gz)
I see it found lua but it gats a lot of 
Failed to guess install tag for /usr/share/geeqie/applications/camera-import.desktop
and the lua.h from what I seen has the lua_createtable etc..
think iot is because mason.build has foreach name : ['lua', 'lua5.3', 'lua-5.3', 'lua53']  and 2.0.1 only had lua_dep = dependency('lua5.3',  version : req_version, required : get_option('lua'))
not found and auto disabled it ..

for now I added -Dlua=disabled \

**Comment by andyrtr** [comment]
The build fails here (Arch Linux) when linking with clang++, linking works with gnu g++ with lua disabled and fails for g++ as well with lua enabled.

**Comment by caclark** [comment]
I use Ubuntu and build Geeqie via meson. I can compile and run with either lua5.3. or lua5.4.

It seems possible that the problem is within the build system you are using - do you have both `liblua5.3-dev` and `liblua5.4-dev` installed?

**Comment by tomaszg7** [comment]
In my case, I'm on Gentoo and we don't have -dev packages, everything is built and compiled locally and all headers are always present. Anyway, lack of dev packages would cause a compiling problem, not a linking problem.

**Comment by oneforall2** [comment]
yeah same here have just lua5.4 .. I wouldn't be surprised if its compiling for you with 5.3 since you have both..

**Comment by voyageur** [comment]
Downstream Gentoo bug: https://bugs.gentoo.org/909302

Locally I have lua 5.1, 5.3, 5.4 and building geeqie with 5.4 - this worked with geeqie 2.0 but fails with similar error to this bug in 2.1

**Comment by mowgli** [comment]
Hi,

Am Di den 27. Jun 2023 um 17:38 schrieb Colin Clark:
> I really have no idea about this... but is the fact that Geeqie is now c++ relevant?
> 
> In some sample code I have seen:
> 
> #ifdef __cplusplus
>   extern "C" {
>     #include "lua.h"
>     #include "lualib.h"
>     #include "lauxlib.h"
>   }
> #endif //__cplusplus

I'll have a look into.

I think that it is caused by c++ conversion but I just have to dive into
all the changes that I missed in the last 3 years.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen ***@***.***>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by xsdg** [comment]
For the folks who are encountering this issue, please respond with the following info:
1) The version of your compiler (please include the full output of, for example, `g++ --version`)
2) The version of your linker (please include the full output of, for example, `ld --version`)
3) The full version of whichever package provides your lua include files (so for instance, on Debian, I'm testing against `liblua5.3-dev` version 5.3.6-2, and `liblua5.4-dev` version 5.4.4-3)

**Comment by xsdg** [comment]
I'm on Debian and have not yet figured out how to repro this issue.

1) ```
    $g++ --version
    g++ (Debian 12.2.0-14) 12.2.0
    Copyright (C) 2022 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    ```

2) ```
    $ld --version
    GNU ld (GNU Binutils for Debian) 2.40
    Copyright (C) 2023 Free Software Foundation, Inc.
    This program is free software; you may redistribute it under the terms of
    the GNU General Public License version 3 or (at your option) a later version.
    This program has absolutely no warranty.
    ```

3) As mentioned above, I've tried with `liblua5.3-dev` version 5.3.6-2 and `liblua5.4-dev` version 5.4.4-3.  Both of those compiled and linked without issue for me.

**Comment by xsdg** [comment]
Okay, still digging, but I _suspect_ that this is a compilation issue, and not a linking issue.  That said, I still have no way to repro the issue, so I'll need help from someone who sees this reliably.

With my compiler, when I look for strings in `lua.cc.o` (the object file created by compiling `lua.cc`), I see that it has automatically used C linkage (that is, avoiding any name-mangling) for the functions defined in the lua shared library, and C++ linkage (performing name mangling to encode argument and return types) for functions for which that is appropriate.  See below for the command and sample output.

For someone running into this issue, it would be really helpful if you could also look at the symbols generated in your `lua.cc.o` object file.  I suspect that all of the function names will be mangled (especially since the linker errors include argument types, which shouldn't be possible with C linkage)

```
# This looks for strings in lua.cc.o, and prints them
# IFF they start with "_Z" or any lower-case ASCII character, and
# IFF they are after "lua.cc" in the output
$strings build/src/geeqie.p/lua.cc.o | egrep '^_Z|^[a-z]' | sed -n '/lua\.cc/, //p'
lua.cc
_ZL18lua_image_get_pathP9lua_State
_ZL18lua_image_get_nameP9lua_State
_ZL23lua_image_get_extensionP9lua_State
_ZL18lua_image_get_dateP9lua_State
_ZL19lua_image_get_marksP9lua_State
_ZL18lua_image_get_sizeP9lua_State
_ZL18lua_image_get_exifP9lua_State
_ZL18lua_exif_get_datumP9lua_State
_ZZ8lua_initvE12meta_methods
_ZL1L
_ZL13image_methods
_ZL12exif_methods
luaL_checktype
luaL_checkudata
lua_pushstring
lua_type
lua_typename
lua_pushfstring
luaL_argerror
lua_pushnumber
_Z12exif_read_fdP8FileData
lua_newuserdatauv
lua_getfield
lua_setmetatable
luaL_checklstring
_Z21exif_get_data_as_textP8ExifDataPKc
strcmp
strptime
mktime
lua_pushnil
_Z13luaL_typerrorP9lua_StateiPKc
_Z8lua_initv
luaL_newstate
luaL_openlibs
lua_createtable
luaL_setfuncs
lua_pushvalue
lua_setglobal
luaL_newmetatable
lua_settable
lua_settop
_Z13lua_callvalueP8FileDataPKcS2_
_Z10get_rc_dirv
g_build_filename
access
luaL_loadfilex
g_free
lua_tolstring
g_strdup_printf
luaL_loadstring
lua_pcallk
g_strdup
strlen
g_locale_to_utf8
_Z17log_domain_printfPKcS0_z
g_error_free
```

**Comment by xsdg** [comment]
And more broadly, I'm hesitant to "fix" this with explicit `extern "C"`, because we should reasonably be seeing identical behavior between the lua libraries and other C libraries like freetype2, gtk, glib, etc.  So it feels like there must be something happening that's specific to how we compile against or use lua in particular, which feels indicative of a bug somewhere.

**Comment by ulm** [comment]
I have the same issue, and with the command above I get these symbols in lua.cc.o:
```
lua.cc
_ZL18lua_exif_get_datumP9lua_State
_ZL18lua_image_get_exifP9lua_State
_ZL18lua_image_get_pathP9lua_State
_ZL18lua_image_get_nameP9lua_State
_ZL23lua_image_get_extensionP9lua_State
_ZL18lua_image_get_dateP9lua_State
_ZL18lua_image_get_sizeP9lua_State
_ZL19lua_image_get_marksP9lua_State
_ZZ8lua_initvE12meta_methods
_ZL1L
_ZL13image_methods
_ZL12exif_methods
_Z13luaL_typerrorP9lua_StateiPKc
_Z8lua_typeP9lua_Statei
_Z12lua_typenameP9lua_Statei
_Z15lua_pushfstringP9lua_StatePKcz
_Z13luaL_argerrorP9lua_StateiPKc
_Z14luaL_checktypeP9lua_Stateii
_Z15luaL_checkudataP9lua_StateiPKc
_Z17luaL_checklstringP9lua_StateiPm
_Z21exif_get_data_as_textP8ExifDataPKc
strcmp
strptime
mktime
_Z14lua_pushnumberP9lua_Stated
_Z11lua_pushnilP9lua_State
_Z14lua_pushstringP9lua_StatePKc
_Z12exif_read_fdP8FileData
_Z15lua_newuserdataP9lua_Statem
_Z12lua_getfieldP9lua_StateiPKc
_Z16lua_setmetatableP9lua_Statei
_Z8lua_initv
_Z13luaL_newstatev
_Z13luaL_openlibsP9lua_State
_Z15lua_createtableP9lua_Stateii
_Z13luaL_setfuncsP9lua_StatePK8luaL_Regi
_Z13lua_pushvalueP9lua_Statei
_Z13lua_setglobalP9lua_StatePKc
_Z17luaL_newmetatableP9lua_StatePKc
_Z12lua_settableP9lua_Statei
_Z10lua_settopP9lua_Statei
_Z13lua_callvalueP8FileDataPKcS2_
_Z10get_rc_dirv
g_build_filename
access
_Z14luaL_loadfilexP9lua_StatePKcS2_
g_free
_Z13lua_tolstringP9lua_StateiPm
g_strdup_printf
_Z15luaL_loadstringP9lua_StatePKc
_Z10lua_pcallkP9lua_StateiiilPFiS0_ilE
g_strdup
strlen
g_locale_to_utf8
_Z17log_domain_printfPKcS0_z
g_error_free
g_malloc
```

```
$ g++ --version
g++ (Gentoo 12.3.1_p20230623 p2) 12.3.1 20230623
```
```
$ ld --version
GNU ld (Gentoo 2.40 p5) 2.40.0
```
Building with lua-5.3.6 (Gentoo package dev-lang/lua-5.3.6-r102).

**Comment by xsdg** [comment]
Okay, so lua is definitely an extremely special case, and it has distro-specific behaviors \*sigh\*

From the Lua website, "Lua is implemented in pure ANSI C and compiles unmodified in all platforms that have an ANSI C compiler. Lua also compiles cleanly as C++."

Debian-based distros (so, including Ubuntu) include this downstream patch, which uses C linkage for lua API functions when compiled with a C++ compiler:
https://sources.debian.org/patches/lua5.3/5.3.6-2/0003-extern_C.patch/

Upstream lua _does not_ include that behavior:
https://github.com/lua/lua/blob/ea39042e13645f63713425c05cc9ee4cfdcf0a40/luaconf.h#L297

So on distributions without that downstream patch, it is expected that lua API calls are compiled with C++ linkage (including name mangling).

That said, for this to work, there would need to be a C version of the shared library (which provides symbols without name mangling) as well as a C++ version (which provides name-mangled symbols).  I'm guessing that this doesn't happen, which explains the linker error on those distros -- it's compiling an object file with C++ linkage, and is attempting to link against a shared library that still has C linkage.

**Comment by xsdg** [comment]
Adding to the confusion, the lua source package includes a file, `lua.hpp`, with these contents:
```
// lua.hpp
// Lua header files for C++
// <<extern "C">> not supplied automatically because Lua also compiles as C++

extern "C" {
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
}
```
This file exists in many places:
1) https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-870.60.4/tools/hidScript/lua/src/lua.hpp.auto.html
2) https://fuchsia.googlesource.com/third_party/lua/+/refs/heads/main/src/lua.hpp
3) https://github.com/aerospike/lua/blob/master/etc/lua.hpp

Unfortunately, one of the places this file _does not_ exist is the lua github repository:
https://github.com/lua/lua/blob/v5.4.6/lua.hpp (this link does not work)

However, it is present in lua's source package for each version, for instance:
https://www.lua.org/ftp/lua-5.4.6.tar.gz

This is discussed on the lua mailing list here:
http://lua-users.org/lists/lua-l/2023-03/msg00013.html

So distributions (like Debian) that build off of the lua source package releases (aka `xxx.tar.gz`) will also include a `lua.hpp` file that would do what we need.  But distributions (like Gentoo) that build off of the lua _github_ repository will not have that file.  >_<


All that said, I believe it's understood what's happening here, and why we're seeing breakage with lua in particular that we aren't seeing with other C libraries.  @caclark's solution from yesterday is the correct one, and should fix this issue.

**Comment by ulm** [comment]
> So distributions (like Debian) that build off of the lua source package releases (aka `xxx.tar.gz`) will also include a `lua.hpp` file that would do what we need. But distributions (like Gentoo) that build off of the lua _github_ repository will not have that file. >_<

Gentoo does have it, though:
```
$ cat /usr/include/lua5.4/lua.hpp 
// lua.hpp
// Lua header files for C++
// <<extern "C">> not supplied automatically because Lua also compiles as C++

extern "C" {
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
}
```

**Comment by oneforall2** [comment]
cat /usr/include/lua.hpp

**Comment by oneforall2** [comment]
g++ --version
g++ (GCC) 13.1.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ld --version
GNU ld version 2.40-blade6415
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

**Comment by oneforall2** [comment]
strings /tmp/geeqie-2.1/meson-build/src/geeqie.p/lua.cc.o | egrep '^_Z|^[a-z]' | sed -n '/lua\.cc/, //p'
egrep: warning: egrep is obsolescent; using grep -E
lua.cc
_ZL18lua_image_get_pathP9lua_State
_ZL18lua_image_get_nameP9lua_State
_ZL23lua_image_get_extensionP9lua_State
_ZL18lua_image_get_dateP9lua_State
_ZL19lua_image_get_marksP9lua_State
_ZL18lua_image_get_sizeP9lua_State
_ZL18lua_image_get_exifP9lua_State
_ZL18lua_exif_get_datumP9lua_State
_ZL1L
_ZL13image_methods
_ZZ8lua_initvE12meta_methods
_ZL12exif_methods
_Z14luaL_checktypeP9lua_Stateii
_Z15luaL_checkudataP9lua_StateiPKc
_Z14lua_pushstringP9lua_StatePKc
_Z8lua_typeP9lua_Statei
_Z12lua_typenameP9lua_Statei
_Z15lua_pushfstringP9lua_StatePKcz
_Z13luaL_argerrorP9lua_StateiPKc
_Z14lua_pushnumberP9lua_Stated
_Z12exif_read_fdP8FileData
_Z17lua_newuserdatauvP9lua_Statemi
_Z12lua_getfieldP9lua_StateiPKc
_Z16lua_setmetatableP9lua_Statei
_Z17luaL_checklstringP9lua_StateiPm
_Z21exif_get_data_as_textP8ExifDataPKc
strcmp
strptime
mktime
_Z11lua_pushnilP9lua_State
_Z13luaL_typerrorP9lua_StateiPKc
_Z8lua_initv
_Z13luaL_newstatev
_Z13luaL_openlibsP9lua_State
_Z15lua_createtableP9lua_Stateii
_Z13luaL_setfuncsP9lua_StatePK8luaL_Regi
_Z13lua_pushvalueP9lua_Statei
_Z13lua_setglobalP9lua_StatePKc
_Z17luaL_newmetatableP9lua_StatePKc
_Z12lua_settableP9lua_Statei
_Z10lua_settopP9lua_Statei
_Z13lua_callvalueP8FileDataPKcS2_
_Z10get_rc_dirv
g_build_filename
access
_Z14luaL_loadfilexP9lua_StatePKcS2_
g_free
_Z13lua_tolstringP9lua_StateiPm
g_strdup_printf
_Z15luaL_loadstringP9lua_StatePKc
_Z10lua_pcallkP9lua_StateiiilPFiS0_ilE
g_strdup
strlen
g_locale_to_utf8
_Z17log_domain_printfPKcS0_z
g_error_free
g_malloc

**Comment by alerque** [comment]
I haven't found a way around this yet. Like Gentoo Arch Linux Lua packages *do* supply `lua.hpp`. I've also tried patching those extern-C includes into this project's `src/lua.cc` file, but so far haven't gotten a working build with either Lua 5.3 or 5.4.

**Comment by xsdg** [comment]
@alerque Could you include a diff that shows the code change you made, as well as the output of the object file `strings` command from above when compiled with that change?

A quick test app shows that Colin's change (or using `#include lua.hpp` from `lua.cc` instead of the trio of includes) should do what is needed:

```
$cat test.cc 
                    int bare_fxn();
             extern int extern_fxn();
extern "C"          int extern_c_fxn();
extern "C" { extern int extern_c_extern_fxn(); };


int main(int argc, char **argv) {
    int out1 = bare_fxn();
    int out2 = extern_fxn();
    int out3 = extern_c_fxn();
    int out4 = extern_c_extern_fxn();
    return 1;
}

$g++ -c -o test.o test.cc

$strings test.o | egrep '^_Z|^[a-z]' | sed -n '/test.cc/, //p'
test.cc
main
_Z8bare_fxnv
_Z10extern_fxnv
extern_c_fxn
extern_c_extern_fxn
```

**Comment by oneforall2** [comment]
just got this patch from archlinux:

--- geeqie-2.1/src/lua.cc	2023-06-17 14:12:30.000000000 +0200
+++ geeqie-2.1/src/lua.cc.new	2023-07-13 11:28:14.538188452 +0200
@@ -24,9 +24,11 @@
 
 #define _XOPEN_SOURCE
 
+extern "C" {
 #include <lua.h>
 #include <lauxlib.h>
 #include <lualib.h>
+}
 
 #include <stdio.h>
 #include <glib.h>
