### ISSUE TITLE
Git version doesn't build with lua-5.3

### ISSUE THREAD

**Issue by HJarausch** [BestImageViewer/geeqie#689]
Trying to build geeqie (GIT) on my Gentoo system fails with
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: lua.o: in function `lua_exif_get_datum':
lua.c:(.text+0x172): undefined reference to `luaL_typerror'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: lua.o: in function `lua_check_image.constprop.0':
lua.c:(.text+0x242): undefined reference to `luaL_typerror'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: lua.o: in function `lua_init':
lua.c:(.text+0x3d0): undefined reference to `luaL_register'

It seems to be related to lua-5.3

It there a fix?
Thanks,
Helmut

**Comment by HJarausch** [comment]
I'd be happy if someone could look at the patch below.
I have created it from several sources on the net where people
try to make there package compatible with lua-5.3

At lest, it does compile, it does not crash and it seems to run fine on
"normal" tasks.

patch for GIT version of Geeqie :+1: 
--- src/lua.c.ORIG	2019-08-05 12:45:12.987005773 +0200
+++ src/lua.c	2019-08-05 12:48:02.988015085 +0200
@@ -41,6 +41,32 @@
 static lua_State *L; /** The LUA object needed for all operations (NOTE: That is
 		       * a upper-case variable to match the documentation!) */
 
+void (luaL_pushmodule) (lua_State *L, const char *modname,
+                                   int sizehint);
+
+void luaL_openlib(lua_State *L, const char *libname,
+                                const luaL_Reg *l, int nup) {
+
+  lua_getglobal(L, libname); 
+  if (lua_isnil(L, -1)) { 
+    lua_pop(L, 1); 
+    lua_newtable(L); 
+  } 
+  luaL_setfuncs(L, l, 0); 
+  lua_setglobal(L, libname);
+}
+
+#define luaL_register(L,n,l)    (luaL_openlib(L,(n),(l),0))
+
+int luaL_typerror (lua_State *L, int narg, const char *tname) {
+  const char *msg = lua_pushfstring(L, "%s expected, got %s",
+                                    tname, luaL_typename(L, narg));
+  return luaL_argerror(L, narg, msg);
+}
+
+
+
+
 static FileData *lua_check_image(lua_State *L, int index)
 {
 	FileData **fd;

**Comment by HJarausch** [comment]
Sorry I posted the wrong version of the patch.
Another try:

`--- a/src/lua.c.ORIG	2019-08-06 19:58:40.594882653 +0200
+++ b/src/lua.c	2019-08-06 19:46:38.777922429 +0200
@@ -40,6 +40,34 @@
 
 static lua_State *L; /** The LUA object needed for all operations (NOTE: That is
 		       * a upper-case variable to match the documentation!) */
+void (luaL_pushmodule) (lua_State *L, const char *modname,
+                                   int sizehint);
+
+void luaL_openlib(lua_State *L, const char *libname,
+                                const luaL_Reg *l, int nup) {
+
+  if ( libname ) {
+    lua_getglobal(L, libname); 
+    if (lua_isnil(L, -1)) { 
+      lua_pop(L, 1); 
+      lua_newtable(L); 
+    }
+  }
+  luaL_setfuncs(L, l, 0); 
+  if ( libname )   lua_setglobal(L, libname);
+}
+
+#define luaL_register(L,n,l)    (luaL_openlib(L,(n),(l),0))
+
+int luaL_typerror (lua_State *L, int narg, const char *tname) {
+  const char *msg = lua_pushfstring(L, "%s expected, got %s",
+                                    tname, luaL_typename(L, narg));
+  return luaL_argerror(L, narg, msg);
+}
+
+
+
+
 
 static FileData *lua_check_image(lua_State *L, int index)
 {
`

**Comment by HJarausch** [comment]
Here as an attachment:
[geeqie-lua53.patch.txt](https://github.com/BestImageViewer/geeqie/files/3476609/geeqie-lua53.patch.txt)

**Comment by mowgli** [comment]
Hi,

I pushed a solution that allow compiling with 5.1 as well as 5.3.

What about the other functions you redefined? As I could find, they are
not needed.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by mowgli** [comment]
Sorry, I completly forget about that fix. Hope it helps.
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by HJarausch** [comment]
OK, luaL_pushmodule is a left over, but
luaL_typerror is called in lua.c

luaL_register is called in lua.c and the redefinition calls luaL_openlib which is missing in Lua 5.3, as well. So it's defined in my patch

**Comment by HJarausch** [comment]
I can confirm that the most recent GIT version compiles and runs fine here without my patch.
