### ISSUE TITLE
Cannot build on Fedora Rawhide (GCC 6.0 problem?)

### ISSUE THREAD

**Issue by russel** [BestImageViewer/geeqie#378]
I can build Git master HEAD fine on Debian Sid (GCC 5.3.1), however on Fedora Rawhide (GCC 6.0.0), I get the following error. I assume the issue is GCC related as I include the exiv2 option in both builds.

```
g++ -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include        -I.. -I.. -g -O2 -MT exiv2.o -MD -MP -MF .deps/exiv2.Tpo -c -o exiv2.o exiv2.cc
In file included from main.h:113:0,
                 from exiv2.cc:59:
typedefs.h:164:40: error: left operand of shift expression ‘(-1 << 8)’ is negative [-fpermissive]
  CHANGE_ERROR_MASK              = (~0) << 8, /* the values below are fatal errors */
                                   ~~~~~^~~~
typedefs.h:164:43: error: enumerator value for ‘CHANGE_ERROR_MASK’ is not an integer constant
  CHANGE_ERROR_MASK              = (~0) << 8, /* the values below are fatal errors */
                                           ^
Makefile:897: recipe for target 'exiv2.o' failed
```

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Russel,

Am Do den 14. Apr 2016 um  9:02 schrieb Russel Winder:
> I can build Git master HEAD fine on Debian Sid (GCC 5.3.1), however on Fedora Rawhide (GCC 6.0.0), I get the following error. I assume the issue is GCC related as I include the exiv2 option in both builds.
> 
> ```
> g++ -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include        -I.. -I.. -g -O2 -MT exiv2.o -MD -MP -MF .deps/exiv2.Tpo -c -o exiv2.o exiv2.cc
> In file included from main.h:113:0,
>                  from exiv2.cc:59:
> typedefs.h:164:40: error: left operand of shift expression ???(-1 << 8)??? is negative [-fpermissive]
>   CHANGE_ERROR_MASK              = (~0) << 8, /* the values below are fatal errors */
>                                    ~~~~~^~~~
> typedefs.h:164:43: error: enumerator value for ???CHANGE_ERROR_MASK??? is not an integer constant
>   CHANGE_ERROR_MASK              = (~0) << 8, /* the values below are fatal errors */
>                                            ^
> Makefile:897: recipe for target 'exiv2.o' failed
> ```

This is a known bug in GCC6. And there is already a bug report on redhat
bugzilla I think.

The construct above is absolute legal C code and widely used. Please
report that bug to GCC people.

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQGcBAEBCgAGBQJXD2kbAAoJEKZ8CrGAGfasccIMAMNR4kRantAPmrNgQqs2mJT1
sFiOE7OTTWZpZKOuyHN5SGbNGBh9BELNOCyzjR6c6ZLmW80IEclAEU/+OQlAdBL5
vsEEX9T/qHaj3xRT7B248q2emEgxYQVE0NEdyDKWAsQUGDGBcAvnkV2cs5PzWtPt
AIuHBVGIGh/mi17USp+hHnOv42Za/ziXvILK162Z86CMxf0o+sDqhufQVmyCPL2V
Z0UjG31qor8jgXJ/dGapsVs3ZmV0U0fELFidPL96uOLy4NFGWsXdOpz1AMScnyla
BvT1Ey2zx3vK6kT4OCsSu98Xz0HArwbyqlBofM3MYZw1FGduXB7BJC42n8XcLh3K
iJYtc7/lH0zSPbX6Yz/jvgVvR0gyw7iBCuMJ87+7++bztVRm14uLfnzi6Opp3z7o
BXJC1lmnCCQeMEDxE+sjvgrCCEJrxJXZoAt+Wu5XG0QwGfUIHP34gdYKjPn/378z
JKEpAkuBlarwshBgwiBC3lEXR14X6lt0WrJpIz//Xg==
=wGVb
-----END PGP SIGNATURE-----

**Comment by lge** [comment]
On Thu, Apr 14, 2016 at 02:55:48AM -0700, Klaus Ethgen wrote:
> Hi Russel,
> 
> Am Do den 14. Apr 2016 um  9:02 schrieb Russel Winder:
> > I can build Git master HEAD fine on Debian Sid (GCC 5.3.1), however on Fedora Rawhide (GCC 6.0.0), I get the following error. I assume the issue is GCC related as I include the exiv2 option in both builds.
> > 
> > ```
> > g++ -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include        -I.. -I.. -g -O2 -MT exiv2.o -MD -MP -MF .deps/exiv2.Tpo -c -o exiv2.o exiv2.cc
> > In file included from main.h:113:0,
> >                  from exiv2.cc:59:
> > typedefs.h:164:40: error: left operand of shift expression ???(-1 << 8)??? is negative [-fpermissive]
> >   CHANGE_ERROR_MASK              = (~0) << 8, /* the values below are fatal errors */
> >                                    ~~~~~^~~~
> > typedefs.h:164:43: error: enumerator value for ???CHANGE_ERROR_MASK??? is not an integer constant
> >   CHANGE_ERROR_MASK              = (~0) << 8, /* the values below are fatal errors */
> >                                            ^
> > Makefile:897: recipe for target 'exiv2.o' failed
> > ```
> 
> This is a known bug in GCC6. And there is already a bug report on redhat
> bugzilla I think.
> 
> The construct above is absolute legal C code and widely used. Please
> report that bug to GCC people.

would explicitly stating "U" help?
 ~0U << 8 

    Lars

**Comment by jwakely** [comment]
Left-shifting a signed negative value is undefined behaviour, see 5.8 [expr.shift] paragraph 2 in the C++ standard.

~0U is fine, because that is not a signed value.

**Comment by russel** [comment]
@mowgli Do you have a pointer to the GCC 6.0.0 bug report? From what @jwakely says, it is not actually a bug in the compiler but undefined behaviour that just happened to work for Geeqie in earlier compilers.

As @lge pointed out, and @jwakely confirmed, adding the U here should solve the problem.

**Comment by jwakely** [comment]
Note I updated my comment. `~0U` avoids undefined behaviour, but changes the value of the enumerator.

If you want a signed value with all but the low 8 bits set, how about `~0xff` ?

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Folks,

Am Do den 14. Apr 2016 um 11:44 schrieb Lars Ellenberg:
> would explicitly stating "U" help?
>  ~0U << 8 

Sure. And it does not hurt (at least not in this case).

Am Do den 14. Apr 2016 um 12:40 schrieb Jonathan Wakely:
> Left-shifting a signed negative value is undefined behaviour, see 5.8 [expr.shift] paragraph 2 in the C++ standard.

Well, the language in use is plain C and not C++! There are several
small differences between that languages; especially when it comes to
different standards. Geeqie is in C99 (as I can tell). And as I can
tell, that operation is absolutely valid and defined in C99.

Am Do den 14. Apr 2016 um 13:21 schrieb Russel Winder:
> @mowgli Do you have a pointer to the GCC 6.0.0 bug report? From what @jwakely says, it is not actually a bug in the compiler but undefined behaviour that just happened to work for Geeqie in earlier compilers.

Not at hand. I have to search for it again too.

Am Do den 14. Apr 2016 um 13:22 schrieb Jonathan Wakely:
> Note I updated my comment. `~0U` avoids undefined behaviour, but changes the value of the enumerator.

In this case this is irrelevant.

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQGcBAEBCgAGBQJXD5BjAAoJEKZ8CrGAGfasinEL/ihInX0tJbKpe1B250VskfvO
M7JAIbmi+DZgv9teo9c8X4MZzHezynIT/RsU9llfUg//+xgmQtCPjq89GSgTqqAZ
Ua2hwtJwAS9/vVFuEP7gGuRb4/1r4OaG7G/fIWn8IXxlGMyPnN+b3l0/bQCSGTEp
3OLfQBwNkFvARRz42xt7ma8ksOu0Emms1qctS6m66gHIJFrK57JYVVekbyikZiVx
Xsf0zOO67i0WH8X6dIFNrXB3Oop8VEePSa+D5+I4p/piOslQaI5VkDbLyY42V2C6
4AD3CNTA4vRKdORmrf4IOcQ/TNh30OUaHNkKl9cjQPcNWxRy7vx1PlYV8nJ7+lhn
liiB3LSLeWgR7X9r3ZIMloyXafOzwO/r/uoXFB/b7LLHI79uadppbqZmxtlmCU3E
7yPbokdsJ0Y8XWQz6EyDfHMfBeiLYQ8NkjJdpG6LYgb5jyuT+o2OUpNO1zBQTmRd
OxuhncnG6HrokfBNWvEAsHRDKhOetRZEIvZV9r7JMg==
=KJ84
-----END PGP SIGNATURE-----

**Comment by jwakely** [comment]
> Well, the language in use is plain C and not C++! There are several
small differences between that languages; especially when it comes to
different standards. Geeqie is in C99 (as I can tell). And as I can
tell, that operation is absolutely valid and defined in C99.

The file being compiled is exiv2.cc, on what planet is that pure C? In any case, it's also undefined in C99, see 6.5.7 paragraph 4 (in C99 or C11).

**Comment by jwakely** [comment]
Also, it doesn't matter what language you think the code is written in, it matters what language you compile it as. Unless the makefiles specify a -std option (such as -std=c99) then GCC 6 will compile C files as C11, and C++ files as C++14.

If you want the code to compile as C99 you need to tell GCC that. But even if you do that, left-shifting a signed negative value is undefined.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Do den 14. Apr 2016 um 14:07 schrieb Jonathan Wakely:
> Also, it doesn't matter what language you think the code is written in, it matters what language you compile it as. Unless the makefiles specify a -std option (such as -std=c99) then GCC 6 will compile C files as C11, and C++ files as C++14.

Well, also C11 does not define that as undefined. Only the right value
must not be negative. (See 6.5.7 in C99 specification, same chapter in
C11 specification)

So, this _is_ a bug in GCC6.

Note that this bug is duplicate of #230 but github does not allow to
merge issues.

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQGcBAEBCgAGBQJXD5l3AAoJEKZ8CrGAGfasAGEL/3yG8UU8OOwdbcYgTE3Mn4dB
EMuzWpEkZaUu8Hs8DmU9qTHErupxJo4wcSpjrHFS+pbU8fnFyr47zKDldeOr9REA
DfOfpcPUzo1c2H1rm9f89n0pE+I6lilsoCC/J15fdo6qLYdW19Rk9LZrwNzBzyn2
3SxMbPlx7xceLwLpBcNBDrOBg8bQVd2MX8H0V0XV58I3ngEQ02o83mnFMQV1OzkW
lmCx8vli46C2E50tBQjoxVAQPmh68Bz66gV4NyWEuCQLV7BRTlj92fOza2O/mbH0
fkb6eqIHrGUa5zyLpypRHoPIQtWqvlk45/yDGB3VeKW58EEHkhGSNQ3tmkOFedIB
a0Ez2WLb1wsHfanEI7Vn81cGnD2O98VRDsRpDSG9gTiAszuYkClylkH2C8fAbOhD
O0LEwSuKQ3NUewgd9XtNIoP9uSwltt/PcFHK2u5wYncfd//W4Q9E8NTtwqKId+Wb
Hbo4fg6XsXKJ75usmMqAorzZW4Qrgjus6AsW3cEYYg==
=BJJK
-----END PGP SIGNATURE-----

**Comment by jwakely** [comment]
Again, the file being compiled is a C++ file, not C.

You are not reading 6.5.7 correctly, you seem to have stopped at paragraph 3, but see the next paragraph which says that for E1 << E2:

> If E1 has an unsigned types [...]. If E1 has a signed type and a non-negative value, [...]; **otherwise, the behavior is undefined**.

C++ has almost the same text.

I'm not going to waste any more time repeating myself, I'll leave you to your code.

**Comment by mowgli** [comment]
Ok, that comment about that it is included in a chain from exiv2.cc makes sense. I still think that it is a bug in GCC.

**Comment by mowgli** [comment]
Ok, I resign. The fix does not harm. Last commit will fix that.

(Gna, github does not support coma separated closes.)

**Comment by russel** [comment]
@mowgli  I can confirm I can now compile and install on Fedora Rawhide with GCC 6.0.0. Thanks for making the fix that allowed this.

**Comment by andreygursky** [comment]
Hi Klaus,
> Ok, that comment about that it is included in a chain from exiv2.cc makes sense.

This was the first I noticed, once I started to search for a good solution. And the following code compiles perfectly unless one uses c++11 and later:
```c++
enum A { bit_mask = (~0) << 8 };
```
```
$ g++-6 -Wall -std=c++03 -c test.cpp
$
```

For c++11 and later the error message has been introduced: https://github.com/gcc-mirror/gcc/commit/2b035ffed1b1e4d778811ff85b3f4c35c62cc1ec more than a year ago. Recently (https://github.com/gcc-mirror/gcc/commit/91d87e2239f2147bb8d60688cc4c34f34f15bcda) this has been relaxed: one can override the error by specifying ```-fpermissive```.

> I still think that it is a bug in GCC.

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68252. The gcc has a bug, that it still doesn't warn about this issue for C. However I admit, that I was also surprised about this limitation. And I'm wondering, why this was chosen for the official C standard. Perhaps this was important for portability/embedded?

@jwakely 
> Note I updated my comment. ~0U avoids undefined behaviour, but changes the value of the enumerator, and so alters the size (and range of valid values) of the enumeration type. That will mean using the mask in a bitwise AND expression with an int will produce a long.

Thanks for your notes. Does it have a practical implication here (example leading to an unexpected result with some value for error and a mask)?

**Comment by russel** [comment]
There was a fairly lengthy debate about this on the ACCU General mailing list, prompted by an email from me about this issue. (ACCU was the Association of C and C++ Users, but covers much more than C and C++ these days, hence dropping the acronym. Almost all the UK C and C++ standards committee members are members of ACCU and are on ACCU General.) You do not have to be a member of ACCU to be on the ACCU General mailing list (but it helps :-), but you have to be on the list to be able to get to the archive.

Overall upshot was that the issue is problematic, that it probably should be undefined behaviour, that implementation defined behaviour was probably a bad idea, and that there is no bug in the compiler per se.

**Comment by jwakely** [comment]
@andreygursky as I said in a comment above:

> If you want a signed int value with all but the low 8 bits set, how about ~0xff ? That should be the correct way to produce the value I believe you want.

Please don't invite me back into this thread by @jwakely'ing me, I'm not interested in wasting any more time here trying to help when it's unwelcome.
